# The path to the helper script
source_path = 'Flutter/podhelper.rb'
load File.expand_path(File.join('..', source_path), __FILE__)

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target) if defined? flutter_additional_ios_build_settings
    target.build_configurations.each do |config|
      # Disable code signing for Pods to avoid CI issues with manual signing
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_INJECT_BASE_ENTITLEMENTS'] = "NO"
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ""
    end
  end
end
