"""Add current_weight, goal_weight, weight_unit to User

Revision ID: 8aa7ba0643a0
Revises: a1b2c3d4e5f6
Create Date: 2026-04-18 13:40:34.067157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa7ba0643a0'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('goal_weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight_unit', sa.String(), nullable=True))
    op.alter_column('users', 'has_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.alter_column('users', 'has_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'weight_unit')
    op.drop_column('users', 'goal_weight')
    op.drop_column('users', 'current_weight')
    # ### end Alembic commands ###
