name: Upload to App Store
on: workflow_dispatch

jobs:
  upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Upload IPA
        env:
          # Extracting multiline secret into a file correctly
          API_KEY: ${{ secrets.APP_STORE_API_KEY }}
          KEY_ID: D7KK8JRYCC
          ISSUER_ID: ada504ee-3c9d-4491-b7b2-db490afe913a
        run: |
          # Create the global directory altool explicitly checks for private keys
          mkdir -p ~/private_keys
          
          # Write the multiline secret from GitHub safely into the file
          cat << 'EOF' > ~/private_keys/AuthKey_${KEY_ID}.p8
          ${{ secrets.APP_STORE_API_KEY }}
          EOF
          
          # Upload the IPA we committed to the repository
          xcrun altool --upload-app \
            --type ios \
            --file gojocalories.ipa \
            --apiKey $KEY_ID \
            --apiIssuer $ISSUER_ID
